# Generated by Django 3.2.7 on 2021-10-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('target', models.CharField(choices=[('_blank', '_blank'), ('_self', '_self')], default='_self', max_length=20, verbose_name='Target')),
                ('pos', models.CharField(choices=[('H', 'Header'), ('F', 'Footer')], max_length=20, verbose_name='Позиция меню')),
            ],
        ),
    ]
