# Generated by Django 3.2.7 on 2021-10-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
