# Generated by Django 3.2.7 on 2021-10-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20211020_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='menu',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Отображать'),
            preserve_default=False,
        ),
    ]
