# Generated by Django 3.2.7 on 2021-10-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20211021_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='menu',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
