# Generated by Django 3.2.7 on 2021-10-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='user',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
