# Generated by Django 3.2.7 on 2021-10-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='article',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
