# Generated by Django 3.2.7 on 2021-09-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='article',
            name='imgalt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255, verbose_name='Средний рейтинг'),
        ),
    ]
