# Generated by Django 3.2.7 on 2021-10-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20211019_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(default=None, upload_to='', verbose_name='Дополнительные фото'),
        ),
    ]
