# Generated by Django 3.2.7 on 2021-09-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210927_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imgalt',
            field=models.CharField(max_length=100, verbose_name='imgalt'),
        ),
    ]
