# Generated by Django 3.2.7 on 2021-10-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20211020_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='P', max_length=100, verbose_name='Статус'),
        ),
    ]
