# Generated by Django 3.2.7 on 2021-10-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='recommended',
            field=models.ManyToManyField(related_name='recommendations', to='blogapp.Article', verbose_name='Рекомендуемые статьи'),
        ),
    ]
